import { builtinModules } from 'module';

import js from '@eslint/js';
import importPlugin from 'eslint-plugin-import';
import jsxA11Y from 'eslint-plugin-jsx-a11y';
import nosecrets from 'eslint-plugin-no-secrets';
import regexopt from 'eslint-plugin-optimize-regex';
import prettier from 'eslint-plugin-prettier';
import promise from 'eslint-plugin-promise';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import simpleImportSort from 'eslint-plugin-simple-import-sort';
import unicorn from 'eslint-plugin-unicorn';
import globals from 'globals';

export default [
  {
    files: ['**/*.{js,jsx}'],
    ignores: ['dist'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
      },
    },
    settings: { react: { version: '18' } },
    plugins: {
      react,
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      'simple-import-sort': simpleImportSort,
      'jsx-a11y': jsxA11Y,
      'optimize-regex': regexopt,
      'no-secrets': nosecrets,
      import: importPlugin,
      prettier,
      promise,
      unicorn,
    },
    rules: {
      ...js.configs.recommended.rules,
      ...react.configs.recommended.rules,
      ...react.configs['jsx-runtime'].rules,
      ...reactHooks.configs.recommended.rules,
      'react/jsx-filename-extension': [
        'warn',
        {
          extensions: ['.js', '.jsx'],
        },
      ],
      'no-underscore-dangle': [
        'error',
        {
          allow: ['_id', '_retry'],
        },
      ],
      camelcase: ['warn', { properties: 'always' }],
      'react/jsx-no-target-blank': ['warn', { allowReferrer: false }],
      'react/no-unescaped-entities': 'warn',
      'react/prop-types': 'off',
      'no-undef': 'error',
      'no-unused-vars': 'warn',
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
      'simple-import-sort/imports': [
        'warn',
        {
          groups: [
            [`^(${builtinModules.join('|')})(/|$)`],
            [
              '^react',
              '^react-router-dom',
              '^react-redux',
              '^@reduxjs/toolkit',
              '^redux-logger',
              '^axios',
              '^chart.js',
              '^chartjs-plugin-datalabels',
              '^react-chartjs-2',
              '^date-fns',
              '^formik',
              '^yup',
              '^@mui/',
              '^@mui/x-date-pickers',
              '^@mui/icons-material',
              '^@mui/material/styles',
              '^@?\\w',
            ],
            [
              '^.*\\/constants($|\\/.*$)',
              '^.*\\/utils($|\\/.*$)',
              '^.*\\/api($|\\/.*$)',
              '^.*\\/rest($|\\/.*$)',
              '^.*\\/hooks($|\\/.*$)',
              '^.*\\/services($|\\/.*$)',
            ],
            [
              '^.*\\/selectors($|\\/.*$)',
              '^.*\\/slices($|\\/.*$)',
              '^.*\\/thunks($|\\/.*$)',
            ],
            ['^.*\\/components($|\\/.*$)'],
            ['^.*\\/store'],
            ['^.*\\/App\\.jsx$'],
            ['^.*\\/pages($|\\/.*$)'],
            ['^\\.\\.(?!/?$)', '^\\.\\./?$'],
            ['^\\./(?=.*/)(?!/?$)', '^\\.(?!/?$)', '^\\./?$'],
            ['^.*\\/assets($|\\/.*$)', '^.*\\/styles($|\\/.*$)', '^.*\\.css$'],
          ],
        },
      ],
      'simple-import-sort/exports': 'warn',
      'import/first': 'error',
      'import/newline-after-import': ['warn', { count: 1 }],
      'import/no-duplicates': 'error',
      'prettier/prettier': 'warn',
      'react/sort-comp': [
        'error',
        {
          order: [
            'static-methods',
            'instance-variables',
            'lifecycle',
            'render',
            '/^handle.+$/',
            '/^on.+$/',
            'everything-else',
          ],
        },
      ],
      'react/jsx-sort-props': [
        'warn',
        {
          ignoreCase: true,
          callbacksLast: true,
          shorthandFirst: true,
          reservedFirst: true,
        },
      ],
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'react/jsx-no-undef': 'error',
      'sort-vars': [
        'warn',
        {
          ignoreCase: true,
        },
      ],
      'no-else-return': ['error', { allowElseIf: false }],
      'lines-between-class-members': [
        'error',
        'always',
        { exceptAfterSingleLine: true },
      ],
      'import/extensions': [
        'warn',
        'never',
        { json: 'always', css: 'always', scss: 'always' },
      ],
      'import/no-extraneous-dependencies': ['error', { devDependencies: true }],
      'react/function-component-definition': [
        'error',
        { namedComponents: 'function-declaration' },
      ],
      'react/jsx-key': 'error',
      'react/jsx-no-constructed-context-values': 'error',
      'react/jsx-no-useless-fragment': ['warn', { allowExpressions: true }],
      'react/no-danger': 'error',
      eqeqeq: 'error',
      'no-unused-expressions': [
        'error',
        {
          allowShortCircuit: true,
          allowTernary: true,
        },
      ],
      'prefer-const': ['warn', { destructuring: 'all' }],
      'no-param-reassign': [
        'error',
        {
          props: true,
          ignorePropertyModificationsFor: ['state', 'acc', 'config'],
        },
      ],
      'prefer-template': 'warn',
      'no-throw-literal': 'error',
      'no-undefined': 'warn',
      'import/no-absolute-path': 'error',
      'capitalized-comments': ['off', 'always'],
      curly: ['warn', 'all'],
      'no-await-in-loop': 'error',
      'no-template-curly-in-string': 'error',
      'require-await': 'error',
      'prefer-promise-reject-errors': 'error',
      'no-useless-concat': 'error',
      'no-useless-return': 'error',
      'no-multiple-empty-lines': ['error', { max: 1 }],
      'prefer-object-spread': 'error',
      'prefer-destructuring': [
        'warn',
        {
          AssignmentExpression: {
            array: false,
            object: false,
          },
          VariableDeclarator: {
            array: true,
            object: true,
          },
        },
      ],
      'no-var': 'error',
      'no-use-before-define': ['error', { functions: true, classes: true }],
      'no-promise-executor-return': 'error',
      'no-useless-backreference': 'error',
      'no-unreachable-loop': 'error',
      'no-implicit-coercion': 'error',
      'no-invalid-this': 'error',
      'consistent-return': 'warn',
      'default-case': 'error',
      'dot-location': ['warn', 'property'],
      'no-lonely-if': 'warn',
      'no-multi-str': 'warn',
      'prefer-spread': 'warn',
      'import/no-mutable-exports': 'error',
      'no-caller': 'error',
      'no-alert': 'error',
      'no-eval': 'error',
      'no-implicit-globals': 'error',
      'no-return-await': 'error',
      'func-name-matching': 'warn',
      'no-array-constructor': 'warn',
      'no-new-object': 'warn',
      'no-continue': 'error',
      'no-multi-assign': 'warn',
      'no-nested-ternary': 'warn',
      'no-useless-call': 'error',
      'no-useless-constructor': 'error',
      'import/no-commonjs': 'error',
      'import/no-useless-path-segments': 'error',
      'no-new-wrappers': 'error',
      strict: ['error', 'never'],
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-implied-eval': 'error',
      'no-loop-func': 'error',
      'no-new': 'error',
      'no-self-compare': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-sequences': 'error',
      'no-warning-comments': 'warn',
      'no-unneeded-ternary': 'error',
      'spaced-comment': 'error',
      'wrap-regex': 'warn',
      'import/no-self-import': 'error',
      'require-atomic-updates': 'error',
      'array-callback-return': 'error',
      'class-methods-use-this': 'error',
      'max-classes-per-file': ['error', 1],
      'no-div-regex': 'error',
      'no-extra-label': 'error',
      'no-floating-decimal': 'error',
      'no-iterator': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'warn',
      'no-new-func': 'error',
      'no-proto': 'error',
      'no-return-assign': 'error',
      'no-void': 'error',
      'prefer-regex-literals': 'error',
      'init-declarations': ['warn', 'always'],
      'no-label-var': 'error',
      'no-undef-init': 'error',
      'new-cap': 'off',
      'new-parens': 'error',
      'no-bitwise': 'warn',
      'no-negated-condition': 'error',
      'one-var': ['warn', 'never'],
      'no-confusing-arrow': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-rename': [
        'error',
        {
          ignoreDestructuring: false,
          ignoreImport: false,
          ignoreExport: false,
        },
      ],
      'symbol-description': 'error',
      'import/exports-last': 'warn',
      'import/no-named-as-default': 'warn',
      'default-case-last': 'error',
      'default-param-last': 'warn',
      'no-constructor-return': 'error',
      'no-octal-escape': 'error',
      'no-script-url': 'error',
      yoda: 'error',
      'operator-assignment': 'error',
      'import/no-named-as-default-member': 'warn',
      'import/unambiguous': 'error',
      'guard-for-in': 'warn',
      'arrow-body-style': 'warn',
      'block-scoped-var': 'error',
      'array-bracket-newline': ['warn', 'consistent'],
      'block-spacing': ['warn', 'always'],
      'max-nested-callbacks': ['error', 5],
      'no-duplicate-imports': 'error',
      'no-empty-function': 'error',
      'no-extra-parens': ['error', 'functions'],
      'no-mixed-operators': [
        'error',
        {
          groups: [
            ['*', '/', '%', '**'],
            ['+', '-'],
            ['&', '|', '^', '~', '<<', '>>', '>>>'],
            ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
            ['&&', '||'],
            ['in', 'instanceof'],
          ],
        },
      ],
      'no-multi-spaces': 'warn',
      'no-trailing-spaces': 'warn',
      'object-curly-newline': ['warn', { consistent: true }],
      'object-shorthand': 'warn',
      'prefer-arrow-callback': 'warn',
      'yield-star-spacing': 'warn',
      'for-direction': 'error',
      'func-call-spacing': 'error',
      'generator-star-spacing': 'error',
      'global-require': 'off',
      'no-mixed-requires': 'error',
      'no-restricted-globals': 'error',
      'one-var-declaration-per-line': ['error', 'always'],
      'vars-on-top': 'error',
      'no-path-concat': 'error',
      'import/no-amd': 'error',
      'no-const-assign': 'error',
      'no-control-regex': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-invalid-regexp': 'error',
      'no-native-reassign': 'error',
      'no-negated-in-lhs': 'error',
      'no-new-symbol': 'error',
      'no-obj-calls': 'error',
      'no-octal': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-unreachable': 'error',
      'no-useless-escape': 'error',
      'require-yield': 'error',
      'valid-typeof': 'error',
      'getter-return': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-ex-assign': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-restricted-syntax': ['error', 'WithStatement'],
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-unused-labels': 'error',
      'no-with': 'error',
      'no-restricted-properties': [
        'error',
        {
          object: 'require',
          property: 'ensure',
          message:
            'Please use import() instead. More info: https://facebook.github.io/create-react-app/docs/code-splitting',
        },
        {
          object: 'System',
          property: 'import',
          message:
            'Please use import() instead. More info: https://facebook.github.io/create-react-app/docs/code-splitting',
        },
      ],
      'comma-dangle': ['off', 'always-multiline'],
      'comma-spacing': [
        'warn',
        {
          before: false,
          after: true,
        },
      ],
      'eol-last': ['error', 'always'],
      'object-curly-spacing': ['warn', 'always'],
      'space-in-parens': ['error', 'never'],
      'promise/always-return': 'warn',
      'promise/no-return-wrap': 'warn',
      'promise/catch-or-return': 'warn',
      'promise/prefer-await-to-then': 'warn',
      'promise/no-nesting': 'warn',
      'no-inline-comments': 'warn',
      'react/no-render-return-value': 'warn',
      'react/jsx-no-duplicate-props': 'error',
      'react/no-unused-state': 'warn',
      'react/require-render-return': 'warn',
      'react/no-unstable-nested-components': ['error', { allowAsProps: true }],
      'react/no-children-prop': 'error',
      'react/jsx-pascal-case': 'error',
      'react/no-unused-prop-types': 'warn',
      'react/jsx-fragments': ['error', 'syntax'],
      'react/display-name': 'error',
      'react/require-default-props': 'warn',
      'react/no-direct-mutation-state': 'error',
      'react/no-multi-comp': ['error', { ignoreStateless: true }],
      'react/no-typos': 'error',
      'react/boolean-prop-naming': [
        'warn',
        { rule: '^(is|has|can)[A-Z]([A-Za-z0-9]?)+' },
      ],
      'react/no-access-state-in-setstate': 'error',
      'react/self-closing-comp': 'warn',
      'react/void-dom-elements-no-children': 'error',
      'optimize-regex/optimize-regex': 'warn',
      'unicorn/no-array-for-each': 'warn',
      'unicorn/prefer-query-selector': 'warn',
      'no-secrets/no-secrets': 'error',
      'jsx-a11y/alt-text': 'warn',
      'jsx-a11y/anchor-is-valid': 'warn',
      'jsx-a11y/no-noninteractive-element-to-interactive-role': 'error',
      'no-console': 'off',
      'no-magic-numbers': [
        'error',
        {
          ignore: [
            -2, -1, 0, 1, 2, 3, 5, 6, 8, 15, 16, 20, 25, 31, 100, 256, 401, 404,
            500, 3000,
          ],
          ignoreArrayIndexes: true,
          enforceConst: true,
          detectObjects: false,
        },
      ],
      // 'react/no-array-index-key': 'warn',
      // 'react/jsx-no-bind': ['warn', { ignoreRefs: true }],
    },
  },
];
