/* eslint-disable camelcase */
const { getUserDetailsByEmail } = require('../utils/sharedFunctions');

async function postgresData() {
  const moderatorDetails = await getUserDetailsByEmail('o.ivanchuk@gmail.com');
  const userDetails = await getUserDetailsByEmail('hanna.shevchenko@gmail.com');

  return {
    categories: [
      {
        title: 'Одяг',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Взуття',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Їжа',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Напої',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Пристрої',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Електроніка',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Обчислювальна техніка',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Побутові пристрої',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Побутова хімія',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Побутова електроніка',
        status: 'rejected',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Транспорт',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Іграшки',
        status: 'pending',
        moderator_id: null,
        moderator_full_name: null,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Книги',
        status: 'pending',
        moderator_id: null,
        moderator_full_name: null,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Медицина',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Послуги',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ],
    currencies: [
      {
        title: 'UAH',
        description: 'Українська гривня',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'USD',
        description: 'Долар США',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'EUR',
        description: 'Євро',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'GBP',
        description: 'Фунт стерлінгів',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'TRY',
        description: 'Турецька ліра',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'AUD',
        description: 'Австралійський долар',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'CAD',
        description: 'Канадський долар',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'CNY',
        description: 'Юань Женьміньбі',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'CZK',
        description: 'Чеська крона',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'DKK',
        description: 'Данська крона',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'HKD',
        description: 'Гонконгівський долар',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'HUF',
        description: 'Форинт',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'INR',
        description: 'Індійська рупія',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'IDR',
        description: 'Рупія',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'ILS',
        description: 'Новий ізраїльський шекель',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'JPY',
        description: 'Єна',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'KZT',
        description: 'Теньге',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'KRW',
        description: 'Вона',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'MXN',
        description: 'Мексиканське песо',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'MDL',
        description: 'Молдовський лей',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'NZD',
        description: 'Новозеландський долар',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'NOK',
        description: 'Норвезька крона',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'RUB',
        description: 'Російський рубль',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'SGD',
        description: 'Сінгапурський долар',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'ZAR',
        description: 'Ренд',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'SEK',
        description: 'Шведська крона',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'CHF',
        description: 'Швейцарський франк',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'EGP',
        description: 'Єгипетський фунт',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'BYN',
        description: 'Білоруський рубль',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'AZN',
        description: 'Азербайджанський манат',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'RON',
        description: 'Румунський лей',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'XDR',
        description: 'СПЗ (спеціальні права запозичення)',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'BGN',
        description: 'Болгарський лев',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'PLN',
        description: 'Злотий',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'DZD',
        description: 'Алжирський динар',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'BDT',
        description: 'Така',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'AMD',
        description: 'Вірменський драм',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'DOP',
        description: 'Домініканське песо',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'IRR',
        description: 'Іранський ріал',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'IQD',
        description: 'Іракський динар',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'KGS',
        description: 'Сом',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'LBP',
        description: 'Ліванський фунт',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'LYD',
        description: 'Лівійський динар',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'MYR',
        description: 'Малайзійський ринггіт',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'MAD',
        description: 'Марокканський дирхам',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'PKR',
        description: 'Пакистанська рупія',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'SAR',
        description: 'Саудівський ріял',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'VND',
        description: 'Донг',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'THB',
        description: 'Бат',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'AED',
        description: 'Дирхам ОАЕ',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'TND',
        description: 'Туніський динар',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'UZS',
        description: 'Узбецький сум',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'TWD',
        description: 'Новий тайванський долар',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'TMT',
        description: 'Туркменський новий манат',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'RSD',
        description: 'Сербський динар',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'TJS',
        description: 'Сомоні',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'GEL',
        description: 'Ларі',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'BRL',
        description: 'Бразильський реал',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ],
    measures: [
      {
        title: 'кг',
        description: 'кілограм',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'г',
        description: 'грам',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'л',
        description: 'літр',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'мл',
        description: 'мілілітр',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'м',
        description: 'метр',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'мм',
        description: 'міліметр',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'см',
        description: 'сантиметр',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'дюйм',
        description: 'дюйм',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'фут',
        description: 'фут',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'м2',
        description: 'квадратний метр',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'шт',
        description: 'одиниця',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'пляшка',
        description: '',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'коробка',
        description: '',
        creator_id: moderatorDetails.id,
        creator_full_name: moderatorDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ],
    shops: [
      {
        title: 'АТБ',
        url: 'https://www.atbmarket.com/',
        logo: '1730713465136-atb.png',
        description: 'Один із найбільших продуктових магазинів в Україні',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Comfy',
        url: 'https://comfy.ua/',
        logo: '1727810661678-comfy.png',
        description: 'Один із найпопулярніших магазинів техніки в Україні',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Епіцентр',
        url: 'https://epicentrk.ua/',
        logo: '1727810677398-Epicentr.png',
        description: 'Найвідоміший будівельний магазин в Україні',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Rozetka',
        url: 'https://rozetka.com.ua/',
        logo: '1733358837502-Rozetka.png',
        description:
          'Найбільший інтернет-магазин в Україні для електроніки та побутових товарів',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Сільпо',
        url: 'https://silpo.ua/',
        logo: '1733358841871-Silpo.png',
        description:
          'Популярна мережа супермаркетів в Україні, що пропонує широкий вибір продуктів та товарів',
        status: 'pending',
        moderator_id: null,
        moderator_full_name: null,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Фокстрот',
        url: 'https://foxtrot.ua/',
        logo: '1733358843327-Foxtrot.jpeg',
        description:
          'Провідний ритейлер електроніки та побутової техніки в Україні',
        status: 'pending',
        moderator_id: null,
        moderator_full_name: null,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Метро',
        url: 'https://www.metro.ua/',
        logo: '1733358844567-Metro.png',
        description:
          'Міжнародний оптовий магазин з великим вибором продуктів та товарів для бізнесу',
        status: 'rejected',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Алло',
        url: 'https://allo.ua/',
        logo: '1733358846085-Allo.png',
        description:
          'Один із популярних магазинів України для електроніки, гаджетів та побутових товарів',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Varus',
        url: 'https://varus.ua/',
        logo: '1733358847810-Varus.jpeg',
        description:
          'Велика мережа продуктових магазинів в Україні з широким асортиментом товарів',
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Ельдорадо',
        url: 'https://eldorado.ua/',
        logo: '1733358849083-Eldorado.jpeg',
        description:
          'Добре відомий ритейлер електроніки та побутової техніки по всій Україні',
        status: 'rejected',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ],
    products: [
      {
        title: 'Футболка',
        category_id: 1,
        status: 'pending',
        moderator_id: null,
        moderator_full_name: null,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Штани',
        category_id: 1,
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Кросівки',
        category_id: 2,
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Черевики',
        category_id: 2,
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Яйця',
        category_id: 3,
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Помідори',
        category_id: 3,
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Пиво',
        category_id: 4,
        status: 'rejected',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Сік',
        category_id: 4,
        status: 'pending',
        moderator_id: null,
        moderator_full_name: null,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Мобільний телефон',
        category_id: 5,
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Навушники',
        category_id: 5,
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Телевізор',
        category_id: 6,
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Камера',
        category_id: 6,
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Ноутбук',
        category_id: 7,
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'SSD-диск',
        category_id: 7,
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Пральна машина',
        category_id: 8,
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Холодильник',
        category_id: 8,
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Мило',
        category_id: 9,
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Пральний порошок',
        category_id: 9,
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Велосипед',
        category_id: 11,
        status: 'approved',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Пелети',
        category_id: 14,
        status: 'rejected',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        title: 'Інтернет',
        category_id: 15,
        status: 'rejected',
        moderator_id: moderatorDetails.id,
        moderator_full_name: moderatorDetails.fullName,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ],
    purchases: [
      {
        product_id: 6,
        amount: 0.5,
        price: 89.5,
        summ: 44.75,
        shop_id: 1,
        measure_id: 1,
        currency_id: 3,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        product_id: 13,
        amount: 1.0,
        price: 49000.0,
        summ: 49000.0,
        shop_id: 2,
        measure_id: 7,
        currency_id: 3,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        product_id: 15,
        amount: 1.0,
        price: 18000.0,
        summ: 18000.0,
        shop_id: 3,
        measure_id: 7,
        currency_id: 3,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        product_id: 16,
        amount: 1.0,
        price: 65000.0,
        summ: 65000.0,
        shop_id: 3,
        measure_id: 7,
        currency_id: 3,
        creator_id: userDetails.id,
        creator_full_name: userDetails.fullName,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ],
  };
}
module.exports = postgresData;
