const CATEGORIES_SLICE_NAME = 'categories';
const CURRENCIES_SLICE_NAME = 'currencies';
const EMAIL_VERIFICATION_SLICE_NAME = 'emailVerification';
const ESTABLISHMENTS_SLICE_NAME = 'establishments';
const EXPENSES_SLICE_NAME = 'expenses';
const MEASURES_SLICE_NAME = 'measures';
const NBU_EXCHANGES_SLICE_NAME = 'nbuExchanges';
const PERMISSIONS_SLICE_NAME = 'permissions';
const PRODUCTS_SLICE_NAME = 'products';
const PROFILE_SLICE_NAME = 'profile';
const ROLES_SLICE_NAME = 'roles';
const STATISTICS_SLICE_NAME = 'statistics';
const USERS_SLICE_NAME = 'users';

export {
  CATEGORIES_SLICE_NAME,
  CURRENCIES_SLICE_NAME,
  EMAIL_VERIFICATION_SLICE_NAME,
  ESTABLISHMENTS_SLICE_NAME,
  EXPENSES_SLICE_NAME,
  MEASURES_SLICE_NAME,
  NBU_EXCHANGES_SLICE_NAME,
  PERMISSIONS_SLICE_NAME,
  PRODUCTS_SLICE_NAME,
  PROFILE_SLICE_NAME,
  ROLES_SLICE_NAME,
  STATISTICS_SLICE_NAME,
  USERS_SLICE_NAME,
};
