const CATEGORIES_SLICE_NAME = 'categories';
const CURRENCIES_SLICE_NAME = 'currencies';
const ESTABLISHMENTS_SLICE_NAME = 'establishments';
const MEASURES_SLICE_NAME = 'measures';
const NBU_EXCHANGES_SLICE_NAME = 'nbuExchanges';
const PRODUCTS_SLICE_NAME = 'products';
const STATISTICS_SLICE_NAME = 'statistics';

export {
  CATEGORIES_SLICE_NAME,
  CURRENCIES_SLICE_NAME,
  ESTABLISHMENTS_SLICE_NAME,
  MEASURES_SLICE_NAME,
  NBU_EXCHANGES_SLICE_NAME,
  PRODUCTS_SLICE_NAME,
  STATISTICS_SLICE_NAME,
};
