### Registration new user
POST http://localhost:5000/api/auth/registration HTTP/1.1
Content-Type: application/json

{
  "fullName": "Will Smith",
  "email": "Will.Smith@Gmail.com",
  "password": "Qwerty12"
}

### Login user
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "WILL.smith@GMAIL.com",
  "password": "Qwerty12"
  # "email": "Updated.User@GMAIL.com",
  # "password": "Qwerty1234567"
}

// ==============================================================

### Login exists customer user
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "Jane.Smith@Gmail.com",
  "password": "Qwerty12"
}

### Login exists administrator user
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "John.Doe@Gmail.com",
  "password": "Qwerty12"
}

// ==============================================================

### Logout user
GET http://localhost:5000/api/auth/logout HTTP/1.1
Content-Type: application/json

### Regenerate Tokens
GET http://localhost:5000/api/auth/refresh HTTP/1.1
Content-Type: application/json

// ==============================================================

### Get list all users
GET http://localhost:5000/api/auth/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldJTEwuc21pdGhAR01BSUwuY29tIiwiaWF0IjoxNzMwMjk0NjI5LCJleHAiOjE3MzAyOTU1Mjl9.DDq8uOfLkQR1C5afCItplpTGIPJ17U-csllTzqCudgo

### Get current user profile
GET http://localhost:5000/api/auth/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkphbmUuU21pdGhAR21haWwuY29tIiwiaWF0IjoxNzMwMjEwMzk3LCJleHAiOjE3MzAyMTEyOTd9.g1jxqw3olobR8beczcXAuJfMLVl07nJ_O-4WvZsDNDQ

### Get user by id
GET http://localhost:5000/api/auth/users/6720e8b4e66d0b35c03fdf0a HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkphbmUuU21pdGhAR21haWwuY29tIiwiaWF0IjoxNzMwMjEwMzk3LCJleHAiOjE3MzAyMTEyOTd9.g1jxqw3olobR8beczcXAuJfMLVl07nJ_O-4WvZsDNDQ

// ==============================================================

### Update user data
PUT http://localhost:5000/api/auth/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldJTEwuc21pdGhAR01BSUwuY29tIiwiaWF0IjoxNzMwMjk0NjI5LCJleHAiOjE3MzAyOTU1Mjl9.DDq8uOfLkQR1C5afCItplpTGIPJ17U-csllTzqCudgo

{
  "id": "67223356726f856f24d0d83e",
  "fullName": "Updated User",
  "email": "Updated.User@GMAIL.com",
  "password": "Qwerty1234567",
  "role": "Administrator"
}

### Delete user by id
DELETE http://localhost:5000/api/auth/delete/67201be61909d2ca1a339bad HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkphbmUuU21pdGhAR21haWwuY29tIiwiaWF0IjoxNzMwMjEwMzk3LCJleHAiOjE3MzAyMTEyOTd9.g1jxqw3olobR8beczcXAuJfMLVl07nJ_O-4WvZsDNDQ