### Get list all categories (status approved, default pagination, without sort)
GET http://localhost:5000/api/categories HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzMzMTczMTg3LCJleHAiOjE3MzMyNTk1ODd9.FKRRdBLfIDb2DNdL9lPuCQ511TctbVPzrUrKm-vD3WE

### Get list all categories (status approved, custom pagination, without sort)
GET http://localhost:5000/api/categories?page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFsZXguSm9obnNvbkBHbWFpbC5jb20iLCJpYXQiOjE3MzMxNDU2NDMsImV4cCI6MTczMzIzMjA0M30.7xzWbk7rBQ0dnaIKsV-Jxyjc2j5bCo2VRImZb4hCkjY

### Get list all categories (status approved, custom pagination, with sort by title (asc))
GET http://localhost:5000/api/categories?sort=title&order=asc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFsZXguSm9obnNvbkBHbWFpbC5jb20iLCJpYXQiOjE3MzMxNDU2NDMsImV4cCI6MTczMzIzMjA0M30.7xzWbk7rBQ0dnaIKsV-Jxyjc2j5bCo2VRImZb4hCkjY

### Get list all categories (status approved, custom pagination, with sort by id (desc))
GET http://localhost:5000/api/categories?sort=id&order=desc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFsZXguSm9obnNvbkBHbWFpbC5jb20iLCJpYXQiOjE3MzMxNDU2NDMsImV4cCI6MTczMzIzMjA0M30.7xzWbk7rBQ0dnaIKsV-Jxyjc2j5bCo2VRImZb4hCkjY

### Get list all categories (status pending, default pagination, without sort)
GET http://localhost:5000/api/categories?status=pending HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFsZXguSm9obnNvbkBHbWFpbC5jb20iLCJpYXQiOjE3MzMxNDU2NDMsImV4cCI6MTczMzIzMjA0M30.7xzWbk7rBQ0dnaIKsV-Jxyjc2j5bCo2VRImZb4hCkjY

### Get list all categories (status pending, custom pagination, without sort)
GET http://localhost:5000/api/categories?status=pending&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFsZXguSm9obnNvbkBHbWFpbC5jb20iLCJpYXQiOjE3MzMxNDU2NDMsImV4cCI6MTczMzIzMjA0M30.7xzWbk7rBQ0dnaIKsV-Jxyjc2j5bCo2VRImZb4hCkjY

### Get list all categories (status rejected, default pagination, without sort)
GET http://localhost:5000/api/categories?status=rejected HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFsZXguSm9obnNvbkBHbWFpbC5jb20iLCJpYXQiOjE3MzMxNDU2NDMsImV4cCI6MTczMzIzMjA0M30.7xzWbk7rBQ0dnaIKsV-Jxyjc2j5bCo2VRImZb4hCkjY

### Get list all categories (status rejected, custom pagination, without sort)
GET http://localhost:5000/api/categories?status=rejected&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFsZXguSm9obnNvbkBHbWFpbC5jb20iLCJpYXQiOjE3MzMxNDU2NDMsImV4cCI6MTczMzIzMjA0M30.7xzWbk7rBQ0dnaIKsV-Jxyjc2j5bCo2VRImZb4hCkjY

### Create category
POST http://localhost:5000/api/categories HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzMzMTczMTg3LCJleHAiOjE3MzMyNTk1ODd9.FKRRdBLfIDb2DNdL9lPuCQ511TctbVPzrUrKm-vD3WE

{
  "title": "Нова категорія"
}

### Get category by id
GET http://localhost:5000/api/categories/16 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzMzMTczMTg3LCJleHAiOjE3MzMyNTk1ODd9.FKRRdBLfIDb2DNdL9lPuCQ511TctbVPzrUrKm-vD3WE

### Moderation category
PATCH http://localhost:5000/api/categories/moderate/16 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik9sZWtzYW5kcmEuSXZhbmNodWtAR21haWwuY29tIiwiaWF0IjoxNzMzMTc4MTMzLCJleHAiOjE3MzMyNjQ1MzN9.9FQpWudlE7nE_dZw7BY-q8KqnCxkP8GTU0cjiC9QlDw

{
  "status": "rejected"
}

### Update category
PATCH http://localhost:5000/api/categories/16 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik9sZWtzYW5kcmEuSXZhbmNodWtAR21haWwuY29tIiwiaWF0IjoxNzMzMTc4MTMzLCJleHAiOjE3MzMyNjQ1MzN9.9FQpWudlE7nE_dZw7BY-q8KqnCxkP8GTU0cjiC9QlDw

{
  "title": "Оновлена назва"
}

### Delete category
DELETE http://localhost:5000/api/categories/16 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzMzMTczMTg3LCJleHAiOjE3MzMyNTk1ODd9.FKRRdBLfIDb2DNdL9lPuCQ511TctbVPzrUrKm-vD3WE
