### Get list all currencies (default pagination)
GET http://localhost:5000/api/currencies HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkphbmUuU21pdGhAR21haWwuY29tIiwiaWF0IjoxNzMyNTg2NTg1LCJleHAiOjE3MzI1ODc0ODV9.TscBXrEBAZlo6T8PS3Y06WYaKqC8jlKK2CPUySiaLb4

### Get list all currencies (custom pagination)
GET http://localhost:5000/api/currencies?page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkphbmUuU21pdGhAR21haWwuY29tIiwiaWF0IjoxNzMyNTg2NTg1LCJleHAiOjE3MzI1ODc0ODV9.TscBXrEBAZlo6T8PS3Y06WYaKqC8jlKK2CPUySiaLb4

### Create currency
POST http://localhost:5000/api/currencies HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFsZXguSm9obnNvbkBHbWFpbC5jb20iLCJpYXQiOjE3MzI1ODQ1MTAsImV4cCI6MTczMjU4NTQxMH0.RpSWoEnsZJmO4vpXfoQbtY87bRL9FpuAX1_gndyJkwc

{
  "title": "New Currency",
  "description": ""
}

### Get currency by id
GET http://localhost:5000/api/currencies/5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFsZXguSm9obnNvbkBHbWFpbC5jb20iLCJpYXQiOjE3MzI1ODQ1MTAsImV4cCI6MTczMjU4NTQxMH0.RpSWoEnsZJmO4vpXfoQbtY87bRL9FpuAX1_gndyJkwc

### Update currency
PATCH http://localhost:5000/api/currencies/5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFsZXguSm9obnNvbkBHbWFpbC5jb20iLCJpYXQiOjE3MzI1ODQ1MTAsImV4cCI6MTczMjU4NTQxMH0.RpSWoEnsZJmO4vpXfoQbtY87bRL9FpuAX1_gndyJkwc

{
  "title": "Updated Currency",
  "description": "test description"
}

### Delete currency
DELETE http://localhost:5000/api/currencies/5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFsZXguSm9obnNvbkBHbWFpbC5jb20iLCJpYXQiOjE3MzEyNDc4OTYsImV4cCI6MTczMTI1MTQ5Nn0.g7POeqqDkPCjEMPhfWaHgaEjt07oQ8cUBAEPBDvuxAk