### Get list all currencies (default pagination, without sort)
GET http://localhost:5000/api/currencies HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI2NDNlMGNhZS1lZDU0LTQ4NmQtYjFjMS04OWM5OTFhZjJhNmUiLCJpYXQiOjE3MzkyMDI2MzYsImV4cCI6MTczOTIwMzUzNn0.OxLFDU0syy9iQugVnmgCwEPOCA5FxhFIl8UFjmIca_I

### Get list all currencies (custom pagination, without sort)
GET http://localhost:5000/api/currencies?page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI2NDNlMGNhZS1lZDU0LTQ4NmQtYjFjMS04OWM5OTFhZjJhNmUiLCJpYXQiOjE3MzkyMDI2MzYsImV4cCI6MTczOTIwMzUzNn0.OxLFDU0syy9iQugVnmgCwEPOCA5FxhFIl8UFjmIca_I

### Get list all currencies (custom pagination, with sort by title (asc))
GET http://localhost:5000/api/currencies?sort=title&order=asc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI2NDNlMGNhZS1lZDU0LTQ4NmQtYjFjMS04OWM5OTFhZjJhNmUiLCJpYXQiOjE3MzkyMDI2MzYsImV4cCI6MTczOTIwMzUzNn0.OxLFDU0syy9iQugVnmgCwEPOCA5FxhFIl8UFjmIca_I

### Get list all currencies (custom pagination, with sort by code (desc))
GET http://localhost:5000/api/currencies?sort=code&order=desc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI2NDNlMGNhZS1lZDU0LTQ4NmQtYjFjMS04OWM5OTFhZjJhNmUiLCJpYXQiOjE3MzkyMDI2MzYsImV4cCI6MTczOTIwMzUzNn0.OxLFDU0syy9iQugVnmgCwEPOCA5FxhFIl8UFjmIca_I

### Get list all currencies (custom pagination, with sort by uuid (desc))
GET http://localhost:5000/api/currencies?sort=uuid&order=desc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI0MWFkYmFlYy1iYWNjLTQ4YzctYjIwYy1jMzYxYTA4NWYxMGIiLCJpYXQiOjE3MzkyMDI3NDIsImV4cCI6MTczOTIwMzY0Mn0.Gr3jecf-a6CQ68aaTGkdaOLk9r9C6ytBNpK_vne4Ca8

### Create currency
POST http://localhost:5000/api/currencies HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI0MWFkYmFlYy1iYWNjLTQ4YzctYjIwYy1jMzYxYTA4NWYxMGIiLCJpYXQiOjE3MzkyMDI3NDIsImV4cCI6MTczOTIwMzY0Mn0.Gr3jecf-a6CQ68aaTGkdaOLk9r9C6ytBNpK_vne4Ca8

{
  "title": "Нова валюта",
  "code": "TST"
}

### Get currency by uuid
GET http://localhost:5000/api/currencies/5d94b4a6-21e1-4369-b08a-12f140ad3f55 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI0MWFkYmFlYy1iYWNjLTQ4YzctYjIwYy1jMzYxYTA4NWYxMGIiLCJpYXQiOjE3MzkyMDI3NDIsImV4cCI6MTczOTIwMzY0Mn0.Gr3jecf-a6CQ68aaTGkdaOLk9r9C6ytBNpK_vne4Ca8

### Update currency
PATCH http://localhost:5000/api/currencies/1c8954d2-b3e9-4284-ac86-b37dd52435b6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI0MWFkYmFlYy1iYWNjLTQ4YzctYjIwYy1jMzYxYTA4NWYxMGIiLCJpYXQiOjE3MzkyMDI3NDIsImV4cCI6MTczOTIwMzY0Mn0.Gr3jecf-a6CQ68aaTGkdaOLk9r9C6ytBNpK_vne4Ca8

{
  "title": "Оновлена валюта",
  "code": "TSS"
}

### Delete currency
DELETE http://localhost:5000/api/currencies/1c8954d2-b3e9-4284-ac86-b37dd52435b6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI0MWFkYmFlYy1iYWNjLTQ4YzctYjIwYy1jMzYxYTA4NWYxMGIiLCJpYXQiOjE3MzkyMDI3NDIsImV4cCI6MTczOTIwMzY0Mn0.Gr3jecf-a6CQ68aaTGkdaOLk9r9C6ytBNpK_vne4Ca8
