### Verification new user email
GET http://localhost:5000/api/email/verify?token=1e9a4906-a77a-45a4-bd79-b41ffcc6b74e HTTP/1.1
Content-Type: application/json

### Resend verification new user email
POST http://localhost:5000/api/email/resend-verify HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMzU3NTU1ZDctMjAyZi00ZDI2LWEyODItMjlhNWRlZTNiM2ViIiwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzcyNDM1ODQsImV4cCI6MTczODUzOTU4NH0.SJbd7LCU5ACu62iHP6g1iya8aiGhuaJDGT5TjCizh20

{
  "email": "nepushkin93@Gmail.com"
}
