### Get list all expenses (default pagination, without sort, period All Time)
GET http://localhost:5000/api/expenses HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI1Yzk0NWU1NC1hYjQwLTRiMjQtYWNlMi0zNTZhNTk3MjE3MzAiLCJpYXQiOjE3Mzk3NzY1MDQsImV4cCI6MTczOTc3NzQwNH0.gFy2dbiJ5ap5oc5rKbnOV8sWFHwGAdBcWnnaBC-vVZY

### Get list all expenses (custom pagination, without sort, period All Time)
GET http://localhost:5000/api/expenses?page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiODA1OWU3OWUtZWNlNy00Zjg0LWI0MzUtZDRmZGIxMjE5ZWVmIiwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzY2NTU5OTUsImV4cCI6MTczNzk1MTk5NX0.NrTY0m_G88nHw2zUN5qlsYzbL7sAWLi02V2R7m9teHs

### Get list all expenses (custom pagination, with sort by product (asc), period All Time)
GET http://localhost:5000/api/expenses?sort=date&order=asc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiODA1OWU3OWUtZWNlNy00Zjg0LWI0MzUtZDRmZGIxMjE5ZWVmIiwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzY2NTU5OTUsImV4cCI6MTczNzk1MTk5NX0.NrTY0m_G88nHw2zUN5qlsYzbL7sAWLi02V2R7m9teHs

### Get list all expenses (custom pagination, with sort by UUID (desc), period Week)
GET http://localhost:5000/api/expenses?ago=week&sort=uuid&order=desc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiODA1OWU3OWUtZWNlNy00Zjg0LWI0MzUtZDRmZGIxMjE5ZWVmIiwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzY2NTU5OTUsImV4cCI6MTczNzk1MTk5NX0.NrTY0m_G88nHw2zUN5qlsYzbL7sAWLi02V2R7m9teHs

### Add expense
POST http://localhost:5000/api/expenses HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI1Yzk0NWU1NC1hYjQwLTRiMjQtYWNlMi0zNTZhNTk3MjE3MzAiLCJpYXQiOjE3Mzk3NzczNzcsImV4cCI6MTczOTc3ODI3N30.X5_xYwaLVe2Q_RJ0wwKboEKBcUYXdek3XN_ZrC02oIA

{
  "product": "Навушники",
  "quantity": 2,
  "measure": "шт",
  "unitPrice": 500,
  "currency": "Українська гривня",
  # "currency": "Долар США",
  # "currency": "Євро",
  "establishment": "Comfy",
  "date": "12 січня 2025"
}

### Get expense by UUID
GET http://localhost:5000/api/expenses/01dd4b2d-fad8-4280-882f-bec20c2649c8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI1Yzk0NWU1NC1hYjQwLTRiMjQtYWNlMi0zNTZhNTk3MjE3MzAiLCJpYXQiOjE3Mzk3NzY1MDQsImV4cCI6MTczOTc3NzQwNH0.gFy2dbiJ5ap5oc5rKbnOV8sWFHwGAdBcWnnaBC-vVZY

### Edit expense by UUID
PATCH http://localhost:5000/api/expenses/fcd66364-7585-41ae-b4f6-71e39adfe5d1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI1Yzk0NWU1NC1hYjQwLTRiMjQtYWNlMi0zNTZhNTk3MjE3MzAiLCJpYXQiOjE3Mzk3NzczNzcsImV4cCI6MTczOTc3ODI3N30.X5_xYwaLVe2Q_RJ0wwKboEKBcUYXdek3XN_ZrC02oIA

{
  "product": "Ноутбук",
  "quantity": 1,
  "measure": "шт",
  "unitPrice": 850.00,
  "currency": "Українська гривня",
  # "currency": "Долар США",
  # "currency": "Євро",
  "establishment": "Епіцентр",
  "date": "15 грудня 2024"
}

### Remove expense by UUID
DELETE http://localhost:5000/api/expenses/e56032f5-72f7-4dd0-908d-39e63c094568 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiODA1OWU3OWUtZWNlNy00Zjg0LWI0MzUtZDRmZGIxMjE5ZWVmIiwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzY2NTU5OTUsImV4cCI6MTczNzk1MTk5NX0.NrTY0m_G88nHw2zUN5qlsYzbL7sAWLi02V2R7m9teHs
