### Get list all expenses (default pagination, without sort, period All Time)
GET http://localhost:5000/api/expenses HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiODA1OWU3OWUtZWNlNy00Zjg0LWI0MzUtZDRmZGIxMjE5ZWVmIiwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzY2NTU5OTUsImV4cCI6MTczNzk1MTk5NX0.NrTY0m_G88nHw2zUN5qlsYzbL7sAWLi02V2R7m9teHs

### Get list all expenses (custom pagination, without sort, period All Time)
GET http://localhost:5000/api/expenses?page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiODA1OWU3OWUtZWNlNy00Zjg0LWI0MzUtZDRmZGIxMjE5ZWVmIiwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzY2NTU5OTUsImV4cCI6MTczNzk1MTk5NX0.NrTY0m_G88nHw2zUN5qlsYzbL7sAWLi02V2R7m9teHs

### Get list all expenses (custom pagination, with sort by product (asc), period All Time)
GET http://localhost:5000/api/expenses?sort=date&order=asc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiODA1OWU3OWUtZWNlNy00Zjg0LWI0MzUtZDRmZGIxMjE5ZWVmIiwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzY2NTU5OTUsImV4cCI6MTczNzk1MTk5NX0.NrTY0m_G88nHw2zUN5qlsYzbL7sAWLi02V2R7m9teHs

### Get list all expenses (custom pagination, with sort by uuid (desc), period Week)
GET http://localhost:5000/api/expenses?ago=week&sort=uuid&order=desc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiODA1OWU3OWUtZWNlNy00Zjg0LWI0MzUtZDRmZGIxMjE5ZWVmIiwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzY2NTU5OTUsImV4cCI6MTczNzk1MTk5NX0.NrTY0m_G88nHw2zUN5qlsYzbL7sAWLi02V2R7m9teHs

### Create expense
POST http://localhost:5000/api/expenses HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiODA1OWU3OWUtZWNlNy00Zjg0LWI0MzUtZDRmZGIxMjE5ZWVmIiwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzY2NTU5OTUsImV4cCI6MTczNzk1MTk5NX0.NrTY0m_G88nHw2zUN5qlsYzbL7sAWLi02V2R7m9teHs

{
  "product": "Навушники",
  "quantity": 1,
  "unitPrice": 100,
  "establishment": "Comfy",
  "measure": "кг",
  # "currency": "Українська гривня",
  "currency": "Долар США",
  # "currency": "Євро",
  "date": "12 січня 2025"
}

### Get expense by uuid
GET http://localhost:5000/api/expenses/e56032f5-72f7-4dd0-908d-39e63c094568 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiODA1OWU3OWUtZWNlNy00Zjg0LWI0MzUtZDRmZGIxMjE5ZWVmIiwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzY2NTU5OTUsImV4cCI6MTczNzk1MTk5NX0.NrTY0m_G88nHw2zUN5qlsYzbL7sAWLi02V2R7m9teHs

### Update expense
PATCH http://localhost:5000/api/expenses/e56032f5-72f7-4dd0-908d-39e63c094568 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiODA1OWU3OWUtZWNlNy00Zjg0LWI0MzUtZDRmZGIxMjE5ZWVmIiwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzY2NTU5OTUsImV4cCI6MTczNzk1MTk5NX0.NrTY0m_G88nHw2zUN5qlsYzbL7sAWLi02V2R7m9teHs

{
  "product": "Ноутбук",
  "quantity": 1,
  "unitPrice": 850.00,
  "establishment": "Comfy",
  "measure": "шт",
  # "currency": "Українська гривня",
  # "currency": "Долар США",
  "currency": "Євро",
  "date": "17 грудня 2024"
}

### Delete expense
DELETE http://localhost:5000/api/expenses/e56032f5-72f7-4dd0-908d-39e63c094568 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiODA1OWU3OWUtZWNlNy00Zjg0LWI0MzUtZDRmZGIxMjE5ZWVmIiwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzY2NTU5OTUsImV4cCI6MTczNzk1MTk5NX0.NrTY0m_G88nHw2zUN5qlsYzbL7sAWLi02V2R7m9teHs
