### Get list all expenses (default pagination, without sort, period All Time)
GET http://localhost:5000/api/expenses HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI4MjM3NTlkOS1kYzg0LTQ2MDctYjQwNC00NWRmM2U3ODZkYzciLCJpYXQiOjE3NDA0ODg5NjcsImV4cCI6MTc0MTc4NDk2N30.60SWgXjgurTGojAyVpzZcf_U7VUViJI5yPHzT6-zQKs

### Get list all expenses (custom pagination, without sort, period All Time)
GET http://localhost:5000/api/expenses?page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiODA1OWU3OWUtZWNlNy00Zjg0LWI0MzUtZDRmZGIxMjE5ZWVmIiwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzY2NTU5OTUsImV4cCI6MTczNzk1MTk5NX0.NrTY0m_G88nHw2zUN5qlsYzbL7sAWLi02V2R7m9teHs

### Get list all expenses (custom pagination, with sort by product (asc), period All Time)
GET http://localhost:5000/api/expenses?sort=date&order=asc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiODA1OWU3OWUtZWNlNy00Zjg0LWI0MzUtZDRmZGIxMjE5ZWVmIiwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzY2NTU5OTUsImV4cCI6MTczNzk1MTk5NX0.NrTY0m_G88nHw2zUN5qlsYzbL7sAWLi02V2R7m9teHs

### Get list all expenses (custom pagination, with sort by UUID (desc), period Week)
GET http://localhost:5000/api/expenses?ago=week&sort=uuid&order=desc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI4MjM3NTlkOS1kYzg0LTQ2MDctYjQwNC00NWRmM2U3ODZkYzciLCJpYXQiOjE3NDA0ODg5NjcsImV4cCI6MTc0MTc4NDk2N30.60SWgXjgurTGojAyVpzZcf_U7VUViJI5yPHzT6-zQKs

### Add expense
POST http://localhost:5000/api/expenses HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI4OTAxNzZmZS00NzgzLTQ5Y2QtOTI3MS03Zjk5OWUzNjY1NDciLCJpYXQiOjE3NDAwOTc0NjIsImV4cCI6MTc0MTM5MzQ2Mn0.DGeeejByXhvwRLcbnyiWSChKD48xdJFP4loPfJK-ekM

{
  "product": "Навушники",
  "quantity": 2,
  "measure": "шт",
  "unitPrice": 500,
  "currency": "Українська гривня",
  # "currency": "Долар США",
  # "currency": "Євро",
  "establishment": "Comfy",
  "date": "12 січня 2025"
}

### Get expense by UUID
GET http://localhost:5000/api/expenses/010b4cd5-0d04-4f02-b82b-a47015c31847 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI4MjM3NTlkOS1kYzg0LTQ2MDctYjQwNC00NWRmM2U3ODZkYzciLCJpYXQiOjE3NDA0ODg5NjcsImV4cCI6MTc0MTc4NDk2N30.60SWgXjgurTGojAyVpzZcf_U7VUViJI5yPHzT6-zQKs

### Edit expense by UUID
PATCH http://localhost:5000/api/expenses/9f6836c1-0018-4360-a5b4-d1705e16998f HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI4OTAxNzZmZS00NzgzLTQ5Y2QtOTI3MS03Zjk5OWUzNjY1NDciLCJpYXQiOjE3NDAwOTc0NjIsImV4cCI6MTc0MTM5MzQ2Mn0.DGeeejByXhvwRLcbnyiWSChKD48xdJFP4loPfJK-ekM

{
  "product": "Ноутбук",
  "quantity": 1,
  "measure": "шт",
  "unitPrice": 850.00,
  "currency": "Українська гривня",
  # "currency": "Долар США",
  # "currency": "Євро",
  "establishment": "Епіцентр",
  "date": "15 грудня 2024"
}

### Remove expense by UUID
DELETE http://localhost:5000/api/expenses/e56032f5-72f7-4dd0-908d-39e63c094568 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiODA1OWU3OWUtZWNlNy00Zjg0LWI0MzUtZDRmZGIxMjE5ZWVmIiwidG9rZW5WZXJzaW9uIjowLCJpYXQiOjE3MzY2NTU5OTUsImV4cCI6MTczNzk1MTk5NX0.NrTY0m_G88nHw2zUN5qlsYzbL7sAWLi02V2R7m9teHs
