### Get list all measures (default pagination, without sort)
GET http://localhost:5000/api/measures HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik8uSXZhbmNodWtAR21haWwuY29tIiwiaWF0IjoxNzM0MDU1MjEyLCJleHAiOjE3MzUzNTEyMTJ9.l1w8mZXWYUM7Uul7Urr9HautKmU502f_W5BpoL7Y5aM

### Get list all measures (custom pagination, without sort)
GET http://localhost:5000/api/measures?page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik8uSXZhbmNodWtAR21haWwuY29tIiwiaWF0IjoxNzM0MDU1MjEyLCJleHAiOjE3MzUzNTEyMTJ9.l1w8mZXWYUM7Uul7Urr9HautKmU502f_W5BpoL7Y5aM

### Get list all measures (custom pagination, with sort by title (asc))
GET http://localhost:5000/api/measures?sort=title&order=asc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik8uSXZhbmNodWtAR21haWwuY29tIiwiaWF0IjoxNzM0MDU1MjEyLCJleHAiOjE3MzUzNTEyMTJ9.l1w8mZXWYUM7Uul7Urr9HautKmU502f_W5BpoL7Y5aM

### Get list all measures (custom pagination, with sort by uuid (desc))
GET http://localhost:5000/api/measures?sort=uuid&order=desc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik8uSXZhbmNodWtAR21haWwuY29tIiwiaWF0IjoxNzM0MDU1MjEyLCJleHAiOjE3MzUzNTEyMTJ9.l1w8mZXWYUM7Uul7Urr9HautKmU502f_W5BpoL7Y5aM

### Create measure
POST http://localhost:5000/api/measures HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik8uSXZhbmNodWtAR21haWwuY29tIiwiaWF0IjoxNzM0MDU1MjEyLCJleHAiOjE3MzUzNTEyMTJ9.l1w8mZXWYUM7Uul7Urr9HautKmU502f_W5BpoL7Y5aM

{
  "title": "Нова одиниця вимірювання",
  "description": ""
}

### Get measure by uuid
GET http://localhost:5000/api/measures/1b7bf265-116f-415d-be02-5471522d3f31 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik8uSXZhbmNodWtAR21haWwuY29tIiwiaWF0IjoxNzM0MDU1MjEyLCJleHAiOjE3MzUzNTEyMTJ9.l1w8mZXWYUM7Uul7Urr9HautKmU502f_W5BpoL7Y5aM

### Update measure
PATCH http://localhost:5000/api/measures/1b7bf265-116f-415d-be02-5471522d3f31 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik8uSXZhbmNodWtAR21haWwuY29tIiwiaWF0IjoxNzM0MDU1MjEyLCJleHAiOjE3MzUzNTEyMTJ9.l1w8mZXWYUM7Uul7Urr9HautKmU502f_W5BpoL7Y5aM

{
  "title": "Оновлена назва одиниці вимірювання",
  "description": "Оновлений опис"
}

### Delete measure
DELETE http://localhost:5000/api/measures/1b7bf265-116f-415d-be02-5471522d3f31 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik8uSXZhbmNodWtAR21haWwuY29tIiwiaWF0IjoxNzM0MDU1MjEyLCJleHAiOjE3MzUzNTEyMTJ9.l1w8mZXWYUM7Uul7Urr9HautKmU502f_W5BpoL7Y5aM
