### Get list of pending items (default pagination, without sort)
GET http://localhost:5000/api/moderation HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMDUzNjFmNzUtOTgyNC00NDcyLTkwYjItMTYyYWZlMWU5OTE2IiwiZW1haWwiOiJvLml2YW5jaHVrQGdtYWlsLmNvbSIsInRva2VuVmVyc2lvbiI6MCwiaWF0IjoxNzM0ODkwNjQzLCJleHAiOjE3MzYxODY2NDN9.vP7_DySVdcbJEFwB57ZTofEsUJxQIw35DV8qZy7MhUM

### Get list of pending items (custom pagination, with sort by uuid (asc))
GET http://localhost:5000/api/moderation?sort=title&order=asc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMDUzNjFmNzUtOTgyNC00NDcyLTkwYjItMTYyYWZlMWU5OTE2IiwiZW1haWwiOiJvLml2YW5jaHVrQGdtYWlsLmNvbSIsInRva2VuVmVyc2lvbiI6MCwiaWF0IjoxNzM0ODkwNjQzLCJleHAiOjE3MzYxODY2NDN9.vP7_DySVdcbJEFwB57ZTofEsUJxQIw35DV8qZy7MhUM

### Moderation category
PATCH http://localhost:5000/api/moderation/categories/7c288c86-1f40-462d-9254-47c5dfd624a9 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMDUzNjFmNzUtOTgyNC00NDcyLTkwYjItMTYyYWZlMWU5OTE2IiwiZW1haWwiOiJvLml2YW5jaHVrQGdtYWlsLmNvbSIsInRva2VuVmVyc2lvbiI6MCwiaWF0IjoxNzM0ODkwNjQzLCJleHAiOjE3MzYxODY2NDN9.vP7_DySVdcbJEFwB57ZTofEsUJxQIw35DV8qZy7MhUM

{
  "status": "rejected"
}

### Moderation product
PATCH http://localhost:5000/api/moderation/products/7327499b-159e-4795-b7ba-f6755c07c7e1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMDUzNjFmNzUtOTgyNC00NDcyLTkwYjItMTYyYWZlMWU5OTE2IiwiZW1haWwiOiJvLml2YW5jaHVrQGdtYWlsLmNvbSIsInRva2VuVmVyc2lvbiI6MCwiaWF0IjoxNzM0ODkwNjQzLCJleHAiOjE3MzYxODY2NDN9.vP7_DySVdcbJEFwB57ZTofEsUJxQIw35DV8qZy7MhUM

{
  "status": "rejected"
}

### Moderation establishment
PATCH http://localhost:5000/api/moderation/establishments/88b1094e-9202-4ad5-b59a-88b81250c56e HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMDUzNjFmNzUtOTgyNC00NDcyLTkwYjItMTYyYWZlMWU5OTE2IiwiZW1haWwiOiJvLml2YW5jaHVrQGdtYWlsLmNvbSIsInRva2VuVmVyc2lvbiI6MCwiaWF0IjoxNzM0ODkwNjQzLCJleHAiOjE3MzYxODY2NDN9.vP7_DySVdcbJEFwB57ZTofEsUJxQIw35DV8qZy7MhUM

{
  "status": "approved"
}