### Get list of pending items (default pagination, without sort)
GET http://localhost:5000/api/moderation HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiIwNzU2MzliZi1mYjJkLTRlZmEtOTMyYS05MjRjNGYyYzVjMmUiLCJpYXQiOjE3NDAxMDQ5MTEsImV4cCI6MTc0MTQwMDkxMX0.FWWVK3mId14fQ22Nm0-S2a6CHblGSYHT2DS4VSm5EPY

### Get list of pending items (custom pagination, with sort by UUID (asc))
GET http://localhost:5000/api/moderation?sort=title&order=asc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiIwNzU2MzliZi1mYjJkLTRlZmEtOTMyYS05MjRjNGYyYzVjMmUiLCJpYXQiOjE3NDAxMDQ5MTEsImV4cCI6MTc0MTQwMDkxMX0.FWWVK3mId14fQ22Nm0-S2a6CHblGSYHT2DS4VSm5EPY

### Moderation category by UUID
PATCH http://localhost:5000/api/moderation/categories/142b971e-8d14-4e91-b107-403e406874ad HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiIwNzU2MzliZi1mYjJkLTRlZmEtOTMyYS05MjRjNGYyYzVjMmUiLCJpYXQiOjE3NDAxMDQ5MTEsImV4cCI6MTc0MTQwMDkxMX0.FWWVK3mId14fQ22Nm0-S2a6CHblGSYHT2DS4VSm5EPY

{
  "status": "rejected"
}

### Moderation product by UUID
PATCH http://localhost:5000/api/moderation/products/4110cacb-9702-4e4b-84f2-571549c99588 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiIwNzU2MzliZi1mYjJkLTRlZmEtOTMyYS05MjRjNGYyYzVjMmUiLCJpYXQiOjE3NDAxMDQ5MTEsImV4cCI6MTc0MTQwMDkxMX0.FWWVK3mId14fQ22Nm0-S2a6CHblGSYHT2DS4VSm5EPY

{
  "status": "approved"
}

### Moderation establishment by UUID
PATCH http://localhost:5000/api/moderation/establishments/d1a48e2c-1400-485a-8905-b0e916d43d23 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiIwNzU2MzliZi1mYjJkLTRlZmEtOTMyYS05MjRjNGYyYzVjMmUiLCJpYXQiOjE3NDAxMDQ5MTEsImV4cCI6MTc0MTQwMDkxMX0.FWWVK3mId14fQ22Nm0-S2a6CHblGSYHT2DS4VSm5EPY

{
  "status": "rejected"
}