### Get list all permissions
GET http://localhost:5000/api/permissions HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI4YjExZmRkMC1lNGY3LTQzOWItYmI1OS03ZDZiNjY4MDNmODEiLCJpYXQiOjE3NDAwMDQ1NTksImV4cCI6MTc0MTMwMDU1OX0.NsComZX0FkQqEwiLGx9TGBhonfO3wBB8lsnfZheDfwM
