### Get list all purchases (default pagination, without sort)
GET http://localhost:5000/api/purchases HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0MTM1MjI3LCJleHAiOjE3MzU0MzEyMjd9.yfBSKFw2SalTcfH4bdaA_MS7FMzvidGroaccqwbmJc8

### Get list all purchases (custom pagination, without sort)
GET http://localhost:5000/api/purchases?page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0MTMyOTU5LCJleHAiOjE3MzU0Mjg5NTl9.Vf9I23BnCnMw6VDhwhCIEbTlDBPWNn_JNL4R7f7HnHM

### Get list all purchases (custom pagination, with sort by product (asc))
GET http://localhost:5000/api/purchases?sort=date&order=asc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0MTMyOTU5LCJleHAiOjE3MzU0Mjg5NTl9.Vf9I23BnCnMw6VDhwhCIEbTlDBPWNn_JNL4R7f7HnHM

### Get list all purchases (custom pagination, with sort by uuid (desc))
GET http://localhost:5000/api/purchases?sort=uuid&order=desc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0MTMyOTU5LCJleHAiOjE3MzU0Mjg5NTl9.Vf9I23BnCnMw6VDhwhCIEbTlDBPWNn_JNL4R7f7HnHM

### Create purchase
POST http://localhost:5000/api/purchases HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0MTMyOTU5LCJleHAiOjE3MzU0Mjg5NTl9.Vf9I23BnCnMw6VDhwhCIEbTlDBPWNn_JNL4R7f7HnHM

{
  "product": "Навушники",
  "amount": 2,
  "price": 500,
  "shop": "Comfy",
  "measure": "кг",
  "currency": "UAH",
  "date": "30 листопада 2024"
}

### Get purchase by uuid
GET http://localhost:5000/api/purchases/824f0495-ee1c-4026-8954-2f9e1803350b HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0MTMyOTU5LCJleHAiOjE3MzU0Mjg5NTl9.Vf9I23BnCnMw6VDhwhCIEbTlDBPWNn_JNL4R7f7HnHM

### Update purchase
PATCH http://localhost:5000/api/purchases/824f0495-ee1c-4026-8954-2f9e1803350b HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0MTMyOTU5LCJleHAiOjE3MzU0Mjg5NTl9.Vf9I23BnCnMw6VDhwhCIEbTlDBPWNn_JNL4R7f7HnHM

{
  "product": "Ноутбук",
  "amount": 1,
  "price": 850.00,
  "shop": "Comfy",
  "measure": "шт",
  "currency": "USD",
  "date": "02 грудня 2024"
}

### Delete purchase
DELETE http://localhost:5000/api/purchases/824f0495-ee1c-4026-8954-2f9e1803350b HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0MTMyOTU5LCJleHAiOjE3MzU0Mjg5NTl9.Vf9I23BnCnMw6VDhwhCIEbTlDBPWNn_JNL4R7f7HnHM
