### Get list all permissions (default pagination)
GET http://localhost:5000/api/roles/permissions HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkphbmUuU21pdGhAR21haWwuY29tIiwiaWF0IjoxNzMxNDQ1MDcyLCJleHAiOjE3MzE0NDg2NzJ9.LIpoKno4gEIhOuF54alva0szlyC0UXX-TZ1RzlOccD8

### Get list all permissions (custom pagination)
GET http://localhost:5000/api/roles/permissions?_page=1&_limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkpvaG4uRG9lQEdtYWlsLmNvbSIsImlhdCI6MTczMDg3NTk3MywiZXhwIjoxNzMwODc5NTczfQ.9bSEtUSpWu2dVyns_qXcErxBrAloATo9bLxMn20dHM4

### Get list all roles
GET http://localhost:5000/api/roles HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkphbmUuU21pdGhAR21haWwuY29tIiwiaWF0IjoxNzMxNDQ1MDcyLCJleHAiOjE3MzE0NDg2NzJ9.LIpoKno4gEIhOuF54alva0szlyC0UXX-TZ1RzlOccD8

### Create role
POST http://localhost:5000/api/roles HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkpvaG4uRG9lQEdtYWlsLmNvbSIsImlhdCI6MTczMTQ0NjE1MiwiZXhwIjoxNzMxNDQ5NzUyfQ.c767dyz-05pcgd2yxxrvItSWcSeSIjQJYBlMIQqU8FQ

{
  "title": "New role",
  "description": "",
  "permissions": ["ADD_CATEGORIES", "ADD_SHOPS", "ADD_PRODUCTS"]
}

### Get role by id
GET http://localhost:5000/api/roles/6733c59555558d3a0383717c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkphbmUuU21pdGhAR21haWwuY29tIiwiaWF0IjoxNzMxNDQ1MDcyLCJleHAiOjE3MzE0NDg2NzJ9.LIpoKno4gEIhOuF54alva0szlyC0UXX-TZ1RzlOccD8

### Update role data
PATCH http://localhost:5000/api/roles/6733c59555558d3a0383717c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkphbmUuU21pdGhAR21haWwuY29tIiwiaWF0IjoxNzMxNDQ1MDcyLCJleHAiOjE3MzE0NDg2NzJ9.LIpoKno4gEIhOuF54alva0szlyC0UXX-TZ1RzlOccD8

{
  "title": "Updated role",
  "description": "Updated description",
  "permissions": []
}

### Delete role by id
DELETE http://localhost:5000/api/roles/672b1351a8dc7c9f08add3b6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkpvaG4uRG9lQEdtYWlsLmNvbSIsImlhdCI6MTczMDg3NTk3MywiZXhwIjoxNzMwODc5NTczfQ.9bSEtUSpWu2dVyns_qXcErxBrAloATo9bLxMn20dHM4