### Get list all roles (default pagination, without sort)
GET http://localhost:5000/api/roles HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI4YjExZmRkMC1lNGY3LTQzOWItYmI1OS03ZDZiNjY4MDNmODEiLCJpYXQiOjE3NDAwMDQ1NTksImV4cCI6MTc0MTMwMDU1OX0.NsComZX0FkQqEwiLGx9TGBhonfO3wBB8lsnfZheDfwM

### Get list all roles (custom pagination, without sort)
GET http://localhost:5000/api/roles?page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiIxMzdkZjQ5Mi0xOTY3LTRhMzgtYjgwNC00MzQzZmQzODEwN2IiLCJpYXQiOjE3MzkyNTI0NDUsImV4cCI6MTczOTI1MzM0NX0.XjexTU3DEXpLhmLZKIXfwSNdUV9EMLErY07cD2aj1kc

### Get list all roles (custom pagination, with sort by title (asc))
GET http://localhost:5000/api/roles?sort=title&order=asc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiIxMzdkZjQ5Mi0xOTY3LTRhMzgtYjgwNC00MzQzZmQzODEwN2IiLCJpYXQiOjE3MzkyNTI0NDUsImV4cCI6MTczOTI1MzM0NX0.XjexTU3DEXpLhmLZKIXfwSNdUV9EMLErY07cD2aj1kc

### Add role
POST http://localhost:5000/api/roles HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI5ZjBlNWNkNi1mNjBkLTQ4ZjEtYTRmZC1jYTY2OGJmNGU0YTgiLCJpYXQiOjE3NDAwMDU2MDUsImV4cCI6MTc0MTMwMTYwNX0.RL-Sf8KiV_X5XsJ9zQryf8D5axZYRa2LN6GroNMiZLw

{
  "title": "Нова роль користувача",
  "description": "",
  "permissions": ["ADD_CATEGORIES", "ADD_ESTABLISHMENTS", "ADD_PRODUCTS"]
}

### Get role by UUID
GET http://localhost:5000/api/roles/d1f3fc36-7a1c-43fe-85c1-f622ea1c1478 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI4YjExZmRkMC1lNGY3LTQzOWItYmI1OS03ZDZiNjY4MDNmODEiLCJpYXQiOjE3NDAwMDQ1NTksImV4cCI6MTc0MTMwMDU1OX0.NsComZX0FkQqEwiLGx9TGBhonfO3wBB8lsnfZheDfwM

### Edit role by UUID
PATCH http://localhost:5000/api/roles/83fd4702-f63a-49a0-aaa7-8c019c0f46f4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI0ZTljMTVlOC0xYjI1LTQ1M2YtODczZC04MGMxMDZmNWFlOTgiLCJpYXQiOjE3Mzk3Njk5OTYsImV4cCI6MTczOTc3MDg5Nn0.0jsMt7ZKlQ5yJdqQqNEYVA1xCb8pG_hEq3lK41xBRx4

{
  "title": "Оновлена назва ролі користувача",
  "description": "Оновлений опис ролі користувача",
  "permissions": ["EDIT_ESTABLISHMENTS"]
}

### Remove role by UUID
DELETE http://localhost:5000/api/roles/8308c5e2-8131-4d5e-a38a-31702d372054 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblZlcnNpb24iOjAsInV1aWQiOiI5OGQ3NjVhNi04YTUzLTQ4MTItYjQxNC03ZjU1OGY5MzFjNzEiLCJpYXQiOjE3MzkyNTI5ODksImV4cCI6MTczOTI1Mzg4OX0.vAV44VVesaqL-_QFjKriarucQKSr8WHLLW-Obl77zCs
