### Get cost by categories per period
GET http://localhost:5000/api/statistics/categories?ago=month&creatorUuid=9cc2ec13-1953-45ff-9247-2f9dea5a7a2c HTTP/1.1
Content-Type: application/json

### Get cost by categories per all time
GET http://localhost:5000/api/statistics/categories HTTP/1.1
Content-Type: application/json

// ==============================================================

### Get cost by establishments per period
GET http://localhost:5000/api/statistics/establishments?ago=month&creatorUuid=32918830-4048-4772-9a1e-b846b4c9b468 HTTP/1.1
Content-Type: application/json

### Get cost by establishments per all time
GET http://localhost:5000/api/statistics/establishments HTTP/1.1
Content-Type: application/json

// ==============================================================

### Get cost by products per period
GET http://localhost:5000/api/statistics/products?ago=month&creatorUuid=32918830-4048-4772-9a1e-b846b4c9b468 HTTP/1.1
Content-Type: application/json

### Get cost by products per all time
GET http://localhost:5000/api/statistics/products HTTP/1.1
Content-Type: application/json