### Get list all users (all users, default pagination, without sort)
GET http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0NzQyMDU4LCJleHAiOjE3MzYwMzgwNTh9.6qCZbI5WzFddsC_YALEHbteMs871KbXM6L37yGErpJY

### Get list all users (all users, custom pagination, without sort)
GET http://localhost:5000/api/users?page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0NDA5NDU0LCJleHAiOjE3MzU3MDU0NTR9.I8zKgy_WtZF2p--0q_CkrPgq_njq463XQwiSj9KYP8c

### Get list all users (all users, custom pagination, with sort by fullName (asc))
GET http://localhost:5000/api/users?sort=fullName&order=asc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0NDA5NDU0LCJleHAiOjE3MzU3MDU0NTR9.I8zKgy_WtZF2p--0q_CkrPgq_njq463XQwiSj9KYP8c

### Get list all users (custom pagination, with sort by uuid (desc))
GET http://localhost:5000/api/users?sort=uuid&order=desc&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0NDA5NDU0LCJleHAiOjE3MzU3MDU0NTR9.I8zKgy_WtZF2p--0q_CkrPgq_njq463XQwiSj9KYP8c

### Get list all users (activated users, default pagination, without sort)
GET http://localhost:5000/api/users?isActivated=true HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0NDA5NDU0LCJleHAiOjE3MzU3MDU0NTR9.I8zKgy_WtZF2p--0q_CkrPgq_njq463XQwiSj9KYP8c

### Get list all users (activated users, custom pagination, without sort)
GET http://localhost:5000/api/users?isActivated=true&page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0NDA5NDU0LCJleHAiOjE3MzU3MDU0NTR9.I8zKgy_WtZF2p--0q_CkrPgq_njq463XQwiSj9KYP8c

### Get list all users (no activated users, default pagination, without sort)
GET http://localhost:5000/api/users?isActivated=false HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0NDA5NDU0LCJleHAiOjE3MzU3MDU0NTR9.I8zKgy_WtZF2p--0q_CkrPgq_njq463XQwiSj9KYP8c

### Get current user profile
GET http://localhost:5000/api/users/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZWRkMTUyMjItNjc1YS00MGMwLWJmMjAtNTlhN2RhMWI4OTI4IiwiZW1haWwiOiJuZXcudXNlckBnbWFpbC5jb20iLCJ0b2tlblZlcnNpb24iOjgsImlhdCI6MTczNDc2NjQ2OCwiZXhwIjoxNzM2MDYyNDY4fQ.GZpgO18Tol3kA1HFA5apyeXXHzc1aa3HJbtTjlxt840

### Get user by id
GET http://localhost:5000/api/users/06165540-5d2f-42c6-92f9-3770a736917a HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik5ldy5Vc2VyQEdtYWlsLmNvbSIsImlhdCI6MTczNDc2MDIzNywiZXhwIjoxNzM2MDU2MjM3fQ.TOdqvNUHYbvIoYjW4SMZtfyUd411wBjMqIIigM4V6Cw

// ==============================================================

### Update user data
PATCH http://localhost:5000/api/users/edd15222-675a-40c0-bf20-59a7da1b8928 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZWRkMTUyMjItNjc1YS00MGMwLWJmMjAtNTlhN2RhMWI4OTI4IiwiZW1haWwiOiJuZXcudXNlckBnbWFpbC5jb20iLCJ0b2tlblZlcnNpb24iOjgsImlhdCI6MTczNDc2NzgzOCwiZXhwIjoxNzM2MDYzODM4fQ.o8ni41jwBLAo7mws2J6ePvIUIsEz4e0I0jbyjCL4VDo

{
  "fullName": "Оновлений користувач",
  "email": "New.User@Gmail.com",
  # "email": "sytnikov.zp@Gmail.com",
  "role": "User"
}

### Update user password
PATCH http://localhost:5000/api/users/change-password/edd15222-675a-40c0-bf20-59a7da1b8928 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZWRkMTUyMjItNjc1YS00MGMwLWJmMjAtNTlhN2RhMWI4OTI4IiwiZW1haWwiOiJuZXcudXNlckBnbWFpbC5jb20iLCJ0b2tlblZlcnNpb24iOjE0LCJpYXQiOjE3MzQ4MDcxMTUsImV4cCI6MTczNjEwMzExNX0.OuXN6lOwzG1c6VHpV8zntzXBJrnkzgO4JTn1zgVSj4Y

{
  "newPassword": "Qwerty1234567",
  "confirmNewPassword": "Qwerty1234567"
}

### Update user photo
PATCH http://localhost:5000/api/users/update-photo/69aae54e-5249-4687-8887-456c479cd847 HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0NDA5NDU0LCJleHAiOjE3MzU3MDU0NTR9.I8zKgy_WtZF2p--0q_CkrPgq_njq463XQwiSj9KYP8c

--boundary
Content-Disposition: form-data; name="userPhoto"; filename="user.png"
Content-Type: image/png

89 50 4E 47 0D 0A 1A 0A 00 00 00 0D 49 48 44 52
00 00 00 10 00 00 00 10 08 06 00 00 00 1F F3 FF
61 00 00 00 19 74 45 58 74 53 6F 66 74 77 61 72
65 00 41 64 6F 62 65 20 49 6D 61 67 65 52 65 61
64 79 71 C9 65 3C 00 00 00 84 49 44 41 54 78 DA

--boundary--

### Remove user photo
PATCH http://localhost:5000/api/users/delete-photo/69aae54e-5249-4687-8887-456c479cd847 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0NDA5NDU0LCJleHAiOjE3MzU3MDU0NTR9.I8zKgy_WtZF2p--0q_CkrPgq_njq463XQwiSj9KYP8c

{
  "photo": null
}

// ==============================================================

### Delete user by id
DELETE http://localhost:5000/api/users/69aae54e-5249-4687-8887-456c479cd847 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ikhhbm5hLlNoZXZjaGVua29AR21haWwuY29tIiwiaWF0IjoxNzM0NDA5NDU0LCJleHAiOjE3MzU3MDU0NTR9.I8zKgy_WtZF2p--0q_CkrPgq_njq463XQwiSj9KYP8c
