### Get list all users (default pagination)
GET http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFsZXguSm9obnNvbkBHbWFpbC5jb20iLCJpYXQiOjE3MzA4MDY4ODQsImV4cCI6MTczMDgwNzc4NH0.rWpa86RyWsK-tPn6DUC42iLo1vHMxgaJ2y--eUtrSGs

### Get list all users (custom pagination)
GET http://localhost:5000/api/users?_page=1&_limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkphbmUuU21pdGhAR21haWwuY29tIiwiaWF0IjoxNzMwODA0ODg5LCJleHAiOjE3MzA4MDU3ODl9.8ZG3o6Y2xc_EoodjKf3Qm-_40bCVTqxOXUyWE6HTCTE

### Get current user profile
GET http://localhost:5000/api/users/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldJTEwuc21pdGhAR01BSUwuY29tIiwiaWF0IjoxNzMwODAyMzI1LCJleHAiOjE3MzA4MDMyMjV9.bVIuvg1oYGhhQaKg4iQKAS-6jzUAx6l42JClkwQty2w

### Get user by id
GET http://localhost:5000/api/users/6729f17c1060a4437ad0c31d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldJTEwuc21pdGhAR01BSUwuY29tIiwiaWF0IjoxNzMwODAyMzI1LCJleHAiOjE3MzA4MDMyMjV9.bVIuvg1oYGhhQaKg4iQKAS-6jzUAx6l42JClkwQty2w

// ==============================================================

### Update user data
PATCH http://localhost:5000/api/users/672a04db11dc1e508e0c6610 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkpvaG4uRG9lQEdtYWlsLmNvbSIsImlhdCI6MTczMDgwNzAyNCwiZXhwIjoxNzMwODA3OTI0fQ.bMHvKbXpN1ay2TUNvLIIdWqoYmXYcIZrfJ6lrKg-33g

{
  "fullName": "Updated User",
  # "email": "Updated.User@GMAIL.com",
  "password": "Qwerty1234567",
  "role": "User"
}

### Update user photo
PATCH http://localhost:5000/api/users/6729f224ca43c7346ccc02d6/photo HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVwZGF0ZWQudXNlckBnbWFpbC5jb20iLCJpYXQiOjE3MzA4MDI0NjAsImV4cCI6MTczMDgwMzM2MH0.jRBX4KhsmhNScWYT_Gzxbh-CdzwnLz6ruOLNuBcxSjE

--boundary
Content-Disposition: form-data; name="userPhoto"; filename="user.png"
Content-Type: image/png

89 50 4E 47 0D 0A 1A 0A 00 00 00 0D 49 48 44 52
00 00 00 10 00 00 00 10 08 06 00 00 00 1F F3 FF
61 00 00 00 19 74 45 58 74 53 6F 66 74 77 61 72
65 00 41 64 6F 62 65 20 49 6D 61 67 65 52 65 61
64 79 71 C9 65 3C 00 00 00 84 49 44 41 54 78 DA

--boundary--

### Remove user photo
PATCH http://localhost:5000/api/users/6729f224ca43c7346ccc02d6/delphoto HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVwZGF0ZWQudXNlckBnbWFpbC5jb20iLCJpYXQiOjE3MzA4MDI0NjAsImV4cCI6MTczMDgwMzM2MH0.jRBX4KhsmhNScWYT_Gzxbh-CdzwnLz6ruOLNuBcxSjE

{
  "photo": null
}

// ==============================================================

### Delete user by id
DELETE http://localhost:5000/api/users/6729f17c1060a4437ad0c31b HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkpvaG4uRG9lQEdtYWlsLmNvbSIsImlhdCI6MTczMDgwNjQ1NSwiZXhwIjoxNzMwODA3MzU1fQ.jnFN96kgm27jKv7_Vkh8A98aYDdzGq1NAcfGfSeBzpA